### ISSUE TITLE
Implement alerts as its own CRD

### ISSUE THREAD

**Issue by ambientsound** [nais/alerterator#1]

**Comment by Kyrremann** [comment]
Kan ikke `action`, `documentation`, og `sla` slås sammen til `description`? Er jo bare ha linjeskift og en "tittel" hvis det er viktig.

**Comment by ambientsound** [comment]
Alternative spec, making `receivers` an array. This way, multiple Slack configurations can be specified but the array part is moved out of the `channels` and `to` fields, allowing for less complexity in the implementation, and more flexibility in the spec.

```
apiVersion: "nais.io/v1alpha1"
kind: "AlertConfig"
metadata:
  name: nais-testapp
  namespace: default
  labels:
    team: aura
spec:
  receivers: # receivers for all alerts below
    - slack:
        channel: '#aura_alerts_dev-fss'
        prependText: '@here | ' # this text will be prepended the Slack alert title
    - email:
        to: 'auravakt@nav.no' # sends email as well
  alerts:
    - name: nais-testapp unavailable # skip name, a description will suffice
      expr: kube_deployment_status_replicas_unavailable{deployment="nais-testapp"} > 0
      for: 2m
      action: kubectl describe pod -l app=nais-testapp
      documentation: https://github.com/navikt/aura-doc/naisvakt/alerts.md#app_unavailable
      sla: respond within 1h, during office hours
    - name: CoreDNS unavailable
      expr: kube_deployment_status_replicas_available{namespace="kube-system", deployment="coredns"} == 0
      for: 1m
      action: kubectl describe pod -l app=nais-testapp
      documentation: https://github.com/navikt/aura-doc/naisvakt/alerts.md#coredns
      sla: respond within 1h, solve within 4h, around the clock
```

**Comment by ambientsound** [comment]
@Kyrremann,

If an error situation is not governed by an SLA, and does not have any documentation, I'd argue that it does not warrant an _ALERT_. Alerts differ from _metrics_ in a fundamental property: they are designed to quickly and effectively inform someone that there is something important gone wrong, and they should stop doing whatever they're doing, and work on the problem instead. The SLA, action and documentation fields are a courtesy to the engineer being woken up at 3am, making their life easier.

We don't have to be opinionated on this. These fields are there simply to guide teams in the right direction, building a good culture, and make it harder to make avoidable mistakes.

**Comment by Kyrremann** [comment]
Så lenge de ikke er påkrevd så skal ikke jeg argumentere i mot disse feltene.

Ref `name`, kanskje bare fjerne? Trenger ikke den med en god beskrivelse.

**Comment by ambientsound** [comment]
Kjøper argumentet om at de ikke trenger være påkrevd.

`name` er allerede ute, tror bare det ble en typo her. Den bør hete `description`. Navnet kan autogenereres basert på `team`-`namespace`-`resourceName`-`serial`. I eksemplet under f.eks `aura-default-nais-testapp-001` og `-002`.

```
apiVersion: "nais.io/v1alpha1"
kind: "AlertConfig"
metadata:
  name: nais-testapp
  namespace: default
  labels:
    team: aura
spec:
  receivers: # receivers for all alerts below
    - slack:
        channel: '#aura_alerts_dev-fss'
        prependText: '@here | ' # this text will be prepended the Slack alert title
    - email:
        to: 'auravakt@nav.no' # sends email as well
  alerts:
    - description: nais-testapp unavailable
      expr: kube_deployment_status_replicas_unavailable{deployment="nais-testapp"} > 0
      for: 2m
      action: kubectl describe pod -l app=nais-testapp
      documentation: https://github.com/navikt/aura-doc/naisvakt/alerts.md#app_unavailable
      sla: respond within 1h, during office hours
    - description: CoreDNS unavailable, there are zero replicas
      expr: kube_deployment_status_replicas_available{namespace="kube-system", deployment="coredns"} == 0
      for: 1m
      action: kubectl describe pod -l app=nais-testapp
      documentation: https://github.com/navikt/aura-doc/naisvakt/alerts.md#coredns
      sla: respond within 1h, solve within 4h, around the clock
```
