### ISSUE TITLE
Mulighet for inhibition rule

### ISSUE THREAD

**Issue by Kyrremann** [nais/alerterator#15]
Det har blitt etterlyst muligheten for inhibition rule, som lar oss skru av andre alerts basert på en alert.
> Inhibition is a concept of suppressing notifications for certain alerts if certain other alerts are already firing.

Med dette kunne man enkelt lagt til regel som skrudde av alerts utenfor arbeidstid, eller skru av alerts som man vet er følge-alerts pga. en annen feil.

```
inhibit_rules:
- source_match:
    alertname: QuietHours
  target_match:
    component: 'data_source'
```

Dette er noe som skal inn i alertmanager-configen.

https://prometheus.io/docs/alerting/alertmanager/#inhibition
https://prometheus.io/docs/alerting/configuration/#inhibit_rule
