### ISSUE TITLE
Feil i alerts knekker alerterator

### ISSUE THREAD

**Issue by Kyrremann** [nais/alerterator#9]
* Hvis noen klarer å spytte inn en alert som ikke validerer, så knekker hele Alerterator. Dette må fikses.
* Vi må også definere specen til å ikke tillate array hvor det egentlig skal være objekter.

Følgende yaml er ikke gyldig. Fjern `-` fra `.receivers.slack` og `.receivers.email`.
```
 receivers:
  - email:
      send_resolved: false
      to: ""
  - slack:
      channel: '#sp-sak'
      prependText: ""
```

Selve feilmeldingen som tipset oss om feilen:
> E0827 10:12:22.749350       1 reflector.go:134] pkg/mod/k8s.io/client-go@v9.0.0+incompatible/tools/cache/reflector.go:95: Failed to list *v1alpha1.Alert: v1alpha1.AlertList.Items: []v1alpha1.Alert: v1alpha1.Alert.Spec: v1alpha1.AlertSpec.Receivers: readObjectStart: expect { or n, but found [, error found in #10 byte of ...\|ceivers":[{"slack":{\|..., bigger context ...\|nd within 1h, during office hours"}],"receivers":[{"slack":{"channel":"#sp-sak"}}]}},{"apiVersion":"\|...
